sudo: required

services:
  - docker

before_install:
  - docker build -t aashishgoyal246/docker-multi-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aashishgoyal246/docker-multi-react npm run test -- --coverage

after_success:
  - docker build -t aashishgoyal246/multi-client ./client 
  - docker build -t aashishgoyal246/multi-nginx ./nginx
  - docker build -t aashishgoyal246/multi-server ./server
  - docker build -t aashishgoyal246/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push aashishgoyal246/multi-client
  - docker push aashishgoyal246/multi-nginx
  - docker push aashishgoyal246/multi-server
  - docker push aashishgoyal246/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: Docker
  env: Docker-2
  bucket_name: "elasticbeanstalk-ap-south-1-364940552322"
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
