sudo: required

services:
  - docker

before_install:
  - docker build -t aashishgoyal246/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aashishgoyal246/docker-react npm run test -- --coverage  

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker"
  env: "Docker-1"
  bucket_name: "elasticbeanstalk-ap-south-1-364940552322"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
